hook.Add("Think", "G-Realms_Adware_blocker_01-sv", function()
	hook.Remove("PlayerSpawn", "z")
end)

hook.Add("Think", "Servius_Anti_Anti_Adware_Blocker_01-sv", function()
	hook.Remove("Think", "G-Realms_Adware_blocker_01-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_02-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_03-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_04-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_05-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_06-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_07-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_08-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_09-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_10-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_11-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_12-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_13-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_14-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_15-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_16-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_17-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_18-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_19-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_20-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_21-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_22-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_23-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_24-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_25-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_26-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_27-sv")
	hook.Remove("Think","G-Realms_Adware_blocker_28-sv")
end)

-- If they bypass this, let me know I can update this to bypass anything they do to bypass my bypass and then they can bypass and then the bypass will bypass the bypass the bypass will bypass the bypass and the bypass will bypass the bypass.